[app]
server_name = "server name"
port = "8080"

[routing]
root_path = "."
origin_root = "/app/v1"

[[routing.origins]]
id = 0
uri = "/start"
file_path = "index.json"
method = "GET"

[[routing.origins]]
id = 1
uri = "/start/1"
file_path = "1/index.json"
method = "GET"

[[routing.origins]]
id = 2
uri = "/start"
file_path = "post.json"
method = "POST"