[app]
server_name = "server name"

[routing]
root_path = "."
origin_root = "/app/v1/test"

[[routing.origins]]
id = 0
uri = "/start/1"
file_path = "/start/1/index.json"
method = "GET"

[[routing.origins]]
id = 1
uri = "/start/2"
file_path = "/start/2/index.json"
method = "GET"

[[routing.origins]]
id = 2
uri = "/start"
file_path = "/start/post.json"
method = "POST"
