name: push all branch
on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Test code
        run: go test -v ./...
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Running golangci-lint
        env:
          GO111MODULE: on
          GOPATH: /home/runner/work/
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          GOCILINT=${GOPATH}/bin/golangci-lint make lint